### ISSUE TITLE
Joining properties does not seem to work

### ISSUE THREAD

**Issue by hoho** [dfilatov/jspath#29]
Readme promises to understand expressions like `(.property1 | .property2 | .propertyN)`.

I try `JSPath.compile('.aa | .bb')` and `JSPath.compile('(.aa | .bb)')` and get `Unexpected token "|"` and `Unexpected token "("` respectively.

0.2.14.

**Comment by dfilatov** [comment]
At present there's no way to use join in top level. 
But you could easily get what you want:
`JSPath.compile('.(.aa | .bb)')`

**Comment by hoho** [comment]
Is it hard to fix?

**Comment by dfilatov** [comment]
You aren't first who asks for this so I try to implement.

**Comment by hoho** [comment]
Sweet! It's logical to have this.

**Comment by dfilatov** [comment]
Will be implemented in 0.3

**Comment by dfilatov** [comment]
@hoho I've released 0.3.0, could you check whether it works as you expected?
