### ISSUE TITLE
Returned object structure is different from original

### ISSUE THREAD

**Issue by lanafrey** [dfilatov/jspath#32]
Here is my code:
var data = {"fields":[
		{"700":{"subfields":[{"a":"author 1"},{"g":"affiliation 1"}]}},
		{"700":{"subfields":[{"a":"author 2"},{"g":"affiliation 2"}]}}	
	]};
var path = '.fields.\"700\".subfields';

After applying the path I am getting:
[	
	{"a":"author 1"},
	{"g":"affiliation 1"},
	{"a":"author 2"},
	{"g":"affiliation 2"}	
]

instead of expected:
[
	[{"a":"author 1"},{"g":"affiliation 1"}],
	[{"a":"author 2"},{"g":"affiliation 2"}]	
]

Is there something I am doing incorrectly?
Thank you, Lana

**Comment by dfilatov** [comment]
Arrays for JSPath are like nodesets in xml and nodesets at the same level are joined
