### ISSUE TITLE
Can't select array

### ISSUE THREAD

**Issue by azazdeaz** [dfilatov/jspath#34]
Hi, great tool!

I think i found a bug: when i try to select an array i get the elements of it instead of the array itself. So the '.array' produces the same result as '.array[0:]'.

example:
```javascript
data = {arr: [1,2,3]};
JSPath.apply('.arr', data);//[1, 2, 3] instead of [[1, 2, 3]]

data = {arr: [1,2,3], b: {arr:[7,8,9]}};
JSPath.apply('..arr', data);//[1, 2, 3, 7, 8, 9] instead of [[1, 2, 3],[7.8.9]]

data = {a: [1,2,3], b: 4};
JSPath.apply('.*', data);//[1, 2, 3, 4] instead of [[1,2,3],4]
```

**Comment by dfilatov** [comment]
Hi!
It's not a bug, it's a feature :) 
Arrays for JSPath are like nodesets in xml and nodesets at the same level are joined.

**Comment by azazdeaz** [comment]
So there is no way to select an array instance with JSPath?:(

**Comment by dfilatov** [comment]
No. Unfortunately, there's no possibility to differ array as data from array as nodeset.

**Comment by azazdeaz** [comment]
I understand, thanks for the answer!

**Comment by deitch** [comment]
Aha. I was looking precisely at this, glad I found the issue.

So if I have:

```js
doc = {
  "a": 1,
  "b": [1]
};

jspath.apply(".a",doc); // returns [1]
jspath.apply(".b",doc); // returns [1]
```

How can I tell that `"a"`'s value is an integer and `"b"`'s value is an array?
