### ISSUE TITLE
Input Json is being modified

### ISSUE THREAD

**Issue by charbel14** [dfilatov/jspath#39]
Hi,

I am feeding the following json structure into the jspath:

var json = {"books":{"book":{"chapters":[{"pages":[],"size":100}]}}};
JSPath.apply("..",json);

checking the JSON object it appears to have been modified to:
"{"books":{"book":{"chapters":[{"pages":["100"],"size":"100"}]}}}"

Pages array now contains an entry that did not exist before.

I tests with the latest 0.3.1

Thanks

**Comment by dfilatov** [comment]
It's definitely a bug.

**Comment by charbel14** [comment]
Thanks,

Tried to debug, but it is kind of hard because the algorithm generated is obfuscated. Maybe I am missing something, but thought it would be nice for the un-minified version to generate a nicely debug-gable/readable version.

Meanwhile what I did is clone the josn being fed in.

Thanks again.

**Comment by dfilatov** [comment]
I've tried to reproduce this bug, but I didn't manage to.
```js
var json = {"books":{"book":{"chapters":[{"pages":[],"size":100}]}}};

jspath.apply('..', json);

console.log(JSON.stringify(json, null, 2));
```
The output is:
```js
{
  "books": {
    "book": {
      "chapters": [
        {
          "pages": [],
          "size": 100
        }
      ]
    }
  }
}
```
Am I missing something?

**Comment by charbel14** [comment]
Hi,

Thanks for taking the time to look into this.

Here is what I 've found:

1 - I created a fiddle and pointed to your depot and tested. all works fine.
2 - I used my local application, and I see the problem.

Puzzled as to what is going on, I checked the version of JSPath, and it looks for some reason the JSPath under lib is version 0.3.1, however the minified version is at 0.3.0.

Is there anything missing in the configs that needs to be updated? I do not understand why the inconsistency.  (Here is my link "https://github.com/dfilatov/jspath.git#0.3.1")

Seems that the fix back in Feb sorted it out. Just need to make sure the proper version is downloaded when I do bower install. (manually for now).

**Comment by dfilatov** [comment]
It's my bad. I added the minified version after I pushed 0.3.1 tag.

**Comment by dfilatov** [comment]
I've republished 0.3.1 so everything should work now. Could you check?

**Comment by charbel14** [comment]
Hi,

Yes I just re-synched  and all is good now.

Thanks for the quick response.

**Comment by dfilatov** [comment]
Thanks for the report!
