### ISSUE TITLE
the result is empty when query a nest arrray

### ISSUE THREAD

**Issue by weinvest** [dfilatov/jspath#42]
json:
[
    {"Id":1, "Name":"michael"},
    {"Id":2, "Name":"tamago"},
    [{"SubId":2, "SubName":"wiliam"}, {"SubId":3, "SubName":"john"}]
]

query:
.[2].SubId

**Comment by dfilatov** [comment]
You'll have to use `.[2].*.SubId` to extract data from nested array.
