### ISSUE TITLE
predicate result is wrong

### ISSUE THREAD

**Issue by weinvest** [dfilatov/jspath#44]
json:
{
    "books" : [
        {
            "id"     : 1,
            "title"  : "Clean Code",
            "author" : { "name" : "Robert C. Martin" },
            "price"  : 17.96
        },
        {
            "id"     : 2,
            "title"  : "Maintainable JavaScript",
            "author" : { "name" : "Nicholas C. Zakas" },
            "price"  : -10
        },
        {
            "id"     : 3,
            "title"  : "Agile Software Development",
            "author" : { "name" : "Robert C. Martin" },
            "price"  : 20
        },
        {
            "id"     : 4,
            "title"  : "JavaScript: The Good Parts",
            "author" : { "name" : "Douglas Crockford" },
            "price"  : 15.67
        }
    ],
    "oks":[{"id":8}]
}

query: .books{ -(.price - 5 + 5 ) == 10 } is null
but query: .books{ -(.price + 5 - 5 ) == 10 } is right

**Comment by dfilatov** [comment]
Hi, @weinvest!
Bug is confirmed.

**Comment by dfilatov** [comment]
Fixed in 0.3.3
