### ISSUE TITLE
Difference between multiple predicates and the logical AND operator

### ISSUE THREAD

**Issue by ghduck** [dfilatov/jspath#48]
Consider the following example JSON:

    var doc = {
        "books" : [
                {
                "id"     : 1,
                "title"  : "Clean Code",
                "author" : { "name" : "Robert C. Martin" },
                "price"  : 7
            },
            {
                "id"     : 2,
                "title"  : "Maintainable JavaScript",
                "author" : { "name" : "Nicholas C. Zakas" },
                "price"  : 12
            },
            {
                "id"     : 3,
                "title"  : "Agile Software Development",
                "author" : { "name" : "Robert C. Martin" },
                "price"  : 15
            }
        ]
    };

I wonder now if there is a difference between the usage of *multiple predicates*,

    JSPath.apply('.books{.price < 15}{.price > 5}.title', doc);
    //yields ["Clean Code", "Maintainable JavaScript"]

or the *logical AND operator* (`&&`),

    JSPath.apply('.books{.price < 15 && .price > 5}.title', doc);
    //yields ["Clean Code", "Maintainable JavaScript"]

to find all books whose price is between `5` and `15`?

**Comment by dfilatov** [comment]
There's no difference. The result will be the same.

**Comment by ghduck** [comment]
Ok thanks :)
Why should multiple predicates still be used when there is an equivalent logical operator which leads to the same result?

**Comment by dfilatov** [comment]
There might be more complicated cases, which can be resolved only using multiple predicates, for instance:
`.a{.b}[0]{.c}`

**Comment by ghduck** [comment]
Fair enough, but now you are use *one* predicate *for each* path expression, not multiple predicates to filter an expression… :worried:

I know that's nitpicking, but on the other hand I really like JSPath—and hope this helps to make it even better. :smile:
