### ISSUE TITLE
[Closed] Why can absolute location paths start with a "." instead of a "^"?

### ISSUE THREAD

**Issue by antstei** [dfilatov/jspath#49]
The documentation says that

> If location path starts with the root (`^`) you are using an absolute location path—your location path begins from the root items.

But all examples use the leading `.`—which locates a context items itself—at the beginning of an absolute path:

```
//The JSON data…
var doc = {
    "books" : [
            {
            "id"     : 1,
            "title"  : "Clean Code",
            "author" : { "name" : "Robert C. Martin" },
            "price"  : 7
        },
        {
            "id"     : 2,
            "title"  : "Maintainable JavaScript",
            "author" : { "name" : "Nicholas C. Zakas" },
            "price"  : 12
        },
        {
            "id"     : 3,
            "title"  : "Agile Software Development",
            "author" : { "name" : "Robert C. Martin" },
            "price"  : 15
        }
    ]
};
// and the query to find all books authors

JSPath.apply('.books.author', doc);
/* [{ name : 'Robert C. Martin' }, { name : 'Nicholas C. Zakas' }, { name : 'Robert C. Martin' }, { name : 'Douglas Crockford' }] */
```

instead of

```
console.log(JSPath.apply('^book.author', doc));
```

which leads to an syntax error since `^` expects a trailing popery starting with a `.`.

Therefore

```
console.log(JSPath.apply('^.books.author', doc));
```

yields the expected data.

---

I wonder now why and when a `^` should be used.

Thanks :smile:

**Comment by dfilatov** [comment]
> I wonder now why and when a ^ should be used.

`^` can be used in case of you need to locate something which is located in another part of your data, for instance:
```js
.a.b.c{.d === ^.e.f}
```

**Comment by ghduck** [comment]
Thanks :+1: 
But AFAIK a JSON object may only have one root element—why does the `^` not return this document root?

**Comment by dfilatov** [comment]
> why does the ^ not return this document root?

I'm not quote sure what you mean. `^` points to root.

**Comment by ghduck** [comment]
> `^` points to root.

When you think of the above example JSON data `book` is the document root.
`^` returns the entire JSON object, since `^.author` yields an empty list.

Instead the `^` should return the same data as a `.*` query does IMO… :smile:

**Comment by dfilatov** [comment]
There could be more than one key on the top level:
```js
var doc = {
    "books" : [...],
    "authors" : [...]
};
```
So I don't see how `^` could point to `books`.

**Comment by ghduck** [comment]
Oops! You are completely right! I mixed up JSON with XML. Yes a JSON structure could be and is usually "anonymous" and doesn't necessarily have a "root member object".

Back to my question; the `^` is used to locate a property when *another context (root)* is already used in the location path and / or object predicate:
```
var doc = {
    "books" : {"a": 1},
    "authors" : {"b": 1}
};

JSPath.apply('.books{.a === ^.authors.b}', doc)
// yields  [Object { a=1}]
```
---

*Many thanks for your support and for this great software* :smile:

**Comment by dfilatov** [comment]
> the ^ is used to locate a property when another context (root) is already used in the location path and / or object predicate?! 

Yes, it is.
