### ISSUE TITLE
Relative positional predicates ? (Question)

### ISSUE THREAD

**Issue by libHive** [dfilatov/jspath#54]
Hi

If I have an object like this :

```
{ "shows" : [
  { "cast" : [ "Fred" ,"Wilma", "Barney" ] },
  { "cast" : [ "Homer" ,"Marge", "Bart" ] },
  { "cast" : [ "Peter" ,"Louis", "Meg" ] }
] }
```

And I'd like to get the first cast member of each show.
If I try the path `'.shows.cast[0]'` I'll only get `'Fred'`

Anything I'm missing that might make this work ?

Thanks

**Comment by dfilatov** [comment]
Hi, @libHive 

You're right, there's no way to choose first item in each show.
