### ISSUE TITLE
cache[path] is not a function

### ISSUE THREAD

**Issue by MShidurkar** [dfilatov/jspath#57]
var doc = {
    "books" : [
        {
            "id"     : 1,
            "title"  : "Clean Code",
            "author" : { "name" : "Robert C. Martin" },
            "price"  : 17.96
        },
        {
            "id"     : 2,
            "title"  : "Maintainable JavaScript",
            "author" : { "name" : "Nicholas C. Zakas" },
            "price"  : 10
        },
        {
            "id"     : 3,
            "title"  : "Agile Software Development",
            "author" : { "name" : "Robert C. Martin" },
            "price"  : 20
        },
        {
            "id"     : 4,
            "title"  : "JavaScript: The Good Parts",
            "author" : { "name" : "Douglas Crockford" },
            "price"  : 15.67
        }
    ]
};

trying to get title using query 

JSPath.apply('.books.title',doc )

getting an error

cache[path] is not a function

querying for the first element as

JSPath.apply('.books.id',doc ) 

getting desire responce but for other elment first throwing an error

**Comment by dfilatov** [comment]
@MShidurkar I've tried to run your code and everything worked as expected. Could you provide more details about your environment?

**Comment by MShidurkar** [comment]
I have this JSON
funionsJSON2= {
			"functions": [
				{
					"name": "trim",
					"parameters": 0,
					"type": "String"
				},
				{
					"name": "length",
					"parameters": 0,
					"type": "String"
				},
				{
					"name": "getTime",
					"paramters": 0,
					"type": "DateTime"
				},
				{
					"name": "getMonth",
					"parameters": 0,
					"type": "DateTime"
				},
				{
					"name": "getDate",
					"parameters": 0,
					"type": "DateTime"
				},
				{
					"name": "concat",
					"parameters": 1,
					"type": "String"
				},
				{
					"name": "substring",
					"parameters": 2,
					"type": "String"
				}
			]
		};

and I am trying to read all names with parameters 0 using query 

var ParameterLessFunctions= JSPath.apply('.functions.name',funionsJSON2,{ paramters : 0 })

but it is not filtering the result also trying to read 
 JSPath.apply('.functions.type',funionsJSON2) throwing error 
cache[path] is not a function

**Comment by dfilatov** [comment]
> but it is not filtering the result 

Substitutions are not intented to be used as filters, checkout documentation. If you need to get all names filtered with parameters 0, use:
```js
JSPath.apply('.functions{.parameters === 0}.name', funionsJSON2));
```

**Comment by MShidurkar** [comment]
I was trying to run on console that's why getting a cache[path] error. Inside functionality is working fine
