### ISSUE TITLE
apply returns unexpected token error when first character is a number

### ISSUE THREAD

**Issue by deitch** [dfilatov/jspath#66]
Try the following:

```js
const doc = { '25': 'a', hello: 'world', '2a' : 'mixed', 'a2': 'ordered' };
jspath.apply('."25"',doc); // returns [ 'a' ] correctly
jspath.apply('.25',doc); // returns error below
jspath.apply('.2a',doc); // returns error below
jspath.apply('.a2',doc); // returns [ 'ordered' ] correctly
```

The error returned is 

```
Error: Unexpected token "0.25"
```

According to the README, valid keys (without requiring quoting) are alphanumerical. Apparently, though, a number does not work at the beginning.

**Comment by dfilatov** [comment]
Hi, @deitch !
Thank you for your note. There was a documentation imperfection. 
I have fixed it.
