### ISSUE TITLE
Get minimum and maximum numbers

### ISSUE THREAD

**Issue by sevban** [dfilatov/jspath#67]
Is it possible to get minimum or maximum number?

Let's say I have a JSON object like this:

```
[
  {
    "InstallmentNumber": 1,
    "Rate": 1
  },
  {
    "InstallmentNumber": 2,
    "Rate": 1
  },
  {
    "InstallmentNumber": 3,
    "Rate": 1
  },
]
```

Then can I get it like this: .{.InstallmentNumber === MAX}

It would be a really cool feature.

**Comment by dfilatov** [comment]
No, it's not possible right now.
