### ISSUE TITLE
null doesn't work with comparison operator

### ISSUE THREAD

**Issue by sevban** [dfilatov/jspath#68]
I want to see objects that have null values in them but I can't.

Example:
`{
   "key":null,
   "key2":"full"
}`

jspath query:
`.{.key == null}`

This returns an empty array.

**Comment by Twinbird24** [comment]
I can confirm that `.key=="null"` produces an empty array. I've ran some tests however, and I've found a potential work-around. The expression `!.key` will return every object where `key` is missing from the object or is set to `null`. If you want to find only objects that have a `key` that is explicitly set to `null` (i.e. excluding those objects from the results where `key` is missing), then you may be out of luck.

**Comment by dfilatov** [comment]
Fixed in 0.4.0
