### ISSUE TITLE
"array does not contain" type filtering

### ISSUE THREAD

**Issue by Twinbird24** [dfilatov/jspath#70]
Given a data set like this:
```
{
    title: "obj1",
    category: [
        "general",
        "feed",
        "repairs"
    ]
},
{
    title: "obj2",
    category: [
        "general",
        "feed"
    ]
}
```
How would I filter to get all objects in which category contains "feed" (which is simply `.category*="feed"`) AND also does not contain "repairs"? Something like `.category*="feed"&&.category!*="repairs"` (which isn't valid) or `.category*="feed"&&.category!="repairs"` (but this still returns both objects above).

Is this something that is possible?

**Comment by dfilatov** [comment]
Hi, @Twinbird24 
Try out this path: `'.{.category === "feed" && !(.category === "repairs")}'`

`!(.category === "repairs")` means "where there's no any category is equal to **repairs**", unlike `.category !== "repairs"` which means "where at least one category is equal to **repairs**,
at the same time

**Comment by Twinbird24** [comment]
That makes sense, thank you!
